### ISSUE TITLE
Stackstorm is not triggering the action with Sensu event handler

### ISSUE THREAD

**Issue by arnabnandy1706** [StackStorm-Exchange/stackstorm-sensu#13]
I have created a rule like below, but the rule is not getting triggered when an event is getting triggered in Sensu.

Please Help !

```yaml
---
name: http-proc-check
description: Rule to check HTTP process in the Sensu clients
pack: sensu
trigger:
   type: sensu.event_handler
criteria:
   trigger.check.name:
      pattern: "proc-http"
     type: "equals"
    trigger.check.output:
     pattern: "CheckProcess CRITICAL*"
      type: "matchregex"
 action:
    ref: "core.local"
    parameters:
     cmd: "echo \"{{trigger}}\" >> /tmp/sensu-sample.out"
  enabled: true
```

Below is the `handler_st2.json` in **Sensu Server**.

```json
{
  "handlers": {
    "st2": {
      "type": "pipe",
      "command": "/opt/sensu/embedded/bin/st2_handler.rb"
    }
  }
}
```
Thanks,
Arnab
